CREATE TABLE MATERIA(
        IdMateria INT IDENTITY(1,1),
        Descricao VARCHAR(50) NOT NULL,
        AreaConhecimento VARCHAR(100) NOT NULL
);

ALTER TABLE MATERIA ADD CONSTRAINT PK_MATERIA
PRIMARY KEY (IdMateria)

CREATE TABLE PROFESSOR(
	IdProfessor INT IDENTITY(1,1),
	Nome VARCHAR(30) NOT NULL,
    Salario DECIMAL(16,2) NOT NULL,
    DataAdmissao DATE NOT NULL, 
    IdMateria INT NOT NULL
);

ALTER TABLE PROFESSOR ADD CONSTRAINT PK_PROFESSOR
PRIMARY KEY (IdProfessor)

ALTER TABLE PROFESSOR ADD CONSTRAINT FK1_PROFESSOR
FOREIGN KEY (IdMateria) REFERENCES MATERIA (IdMateria)

CREATE TABLE ALUNO(
        IdAluno INT IDENTITY(1,1),
        Nome VARCHAR(100) NOT NULL,
        Genero CHAR(1) NOT NULL,
        IdProfessor INT NOT NULL
);

ALTER TABLE ALUNO ADD CONSTRAINT PK_ALUNO
PRIMARY KEY (IdAluno)

ALTER TABLE ALUNO ADD CONSTRAINT FK1_ALUNO
FOREIGN KEY (IdProfessor) REFERENCES PROFESSOR (IdProfessor)